---
version: 2
updates:
  - package-ecosystem: "pip"
    versioning-strategy: "increase"
    target-branch: "main"
    directories:
      - "/django"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "America/New_York"
    groups:
      dependencies:
        patterns:
          - "*"
