name: cicd_rrchnm_org

services:
  app:
    build: .
    image: rrchnm/cicd-testing-django
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=thisisnotasecretkey
      - DJANGO_ALLOWED_HOSTS=localhost
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db_dj
      - DB_USER=user_dj
      - DB_PASS=password
      - OBJ_STORAGE=True
      - OBJ_STORAGE_ACCESS_KEY_ID=TYD5LA84DHFQTMXT72ZD
      - OBJ_STORAGE_SECRET_ACCESS_KEY=wpqxloq0k7Pl5ELF3AhqS+pB+orrd528XB+aO0uo
      - OBJ_STORAGE_BUCKET_NAME=test1.rrchnm.org
      - OBJ_STORAGE_ENDPOINT_URL=https://dev.obj.rrchnm.org
    ports:
      - "1337:8000"
#   command: sh -c "sleep 99999"
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=db_dj
      - POSTGRES_USER=user_dj
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_dj -d db_dj"]
      interval: 2s
      timeout: 5s
      retries: 3

volumes:
  pg_data:
