services:
  app:
    build: .
    image: rrchnm/cicd-testing-django
    container_name: cicd-testing-django--app
    env_file: .env
    ports:
      - "1337:8000"
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py collectstatic --no-input &&
             poetry run python manage.py runserver 0.0.0.0:8000"
   #volumes:
     #- .:/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12
    container_name: cicd-testing-django--db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
   #ports:
     #- "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_dj -d db_dj"]
      interval: 2s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
