---
name: rrchnm-cicd-django-test

services:
  app:
    build: .
    image: rrchnm/cicd-testing-django
    ports:
      - 8000:8000
    volumes:
      - dj-data:/app
     #- .:/app
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=thisisnotasecretkey
      - DJANGO_ALLOWED_HOSTS=localhost
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rrchnm-cicd-django-test
      - DB_USER=rrchnm-cicd-django-test
      - DB_PASSWORD=password
      - ALLAUTH_GITHUB_CLIENT_ID=PLACEHOLDER
      - ALLAUTH_GITHUB_CLIENT_SECRET=PLACEHOLDER
      - ALLAUTH_SLACK_CLIENT_ID=PLACEHOLDER
      - ALLAUTH_SLACK_CLIENT_SECRET=PLACEHOLDER
      - OBJ_STORAGE=True
      - OBJ_STORAGE_ACCESS_KEY_ID=TYD5LA84DHFQTMXT72ZD
      - OBJ_STORAGE_SECRET_ACCESS_KEY=wpqxloq0k7Pl5ELF3AhqS+pB+orrd528XB+aO0uo
      - OBJ_STORAGE_BUCKET_NAME=test1.rrchnm.org
      - OBJ_STORAGE_ENDPOINT_URL=https://dev.obj.rrchnm.org
    command: >
        sh -c "poetry run python3 manage.py migrate &&
               poetry run python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rrchnm-cicd-django-test
      - POSTGRES_USER=rrchnm-cicd-django-test
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rrchnm-cicd-django-test"]
      interval: 2s
      timeout: 5s
      retries: 3

volumes:
  dj-data:
  pg-data:
