name: "Hugo build, release, deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/deploy.yml"
      - "hugo/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: chnm/.github/.github/workflows/hugo--build-release-deploy.yml@main
    secrets: inherit
    with:
      container-registry: "ghcr.io"
      container-image-name: "cicd-testing-website"
      hugo-context-root: "hugo"
      hugo-devl-url: "https://devl.rrchnm.site"
      hugo-prod-url: "https://test1.rrchnm.org"
      
      build-artifact-name: "cicd-testing-website"
      release-tag-name-type: "semvar"
      
      website-devl-fqdn: "dev.test1.rrchnm.org"
      website-prod-fqdn: "test1.rrchnm.org"
      
