name: "Deploy"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: chnm/.github/.github/workflows/hugo--build-release-deploy.yml@v4-artifact-actions
    secrets: inherit
    with:
      container-registry: "ghcr.io"
      container-image-name: "cicd-testing-website"
      hugo-context-root: "."
      hugo-devl-url: "https://devl.rrchnm.site"
      hugo-prod-url: "https://test1.rrchnm.org"
      
      build-artifact-name: "cicd-testing-website"
      release-tag-name-type: "semvar"
      
      website-fqdn: "test1.rrchnm.org"
      
