on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/pull-request.yml"
  workflow_dispatch:

jobs:

  deploy:
    uses: chnm/.github/.github/workflows/ansible--deploy-ssg-website.yml@restricted-workflow
