name: "django workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/django.yml"
      - "django/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-publish:
    uses: chnm/.github/.github/workflows/django--build-publish.yml@main
    secrets: inherit
    with:
      container-registry: "ghcr.io"
      container-image-name: "cicd-testing-django"
      
      django-context-root: "django"

      website-devl-fqdn: "test1.rrchnm.org"
      website-prod-fqdn: "test1.rrchnm.org"

  deploy:
    uses: chnm/.github/.github/workflows/django--deploy.yml@main
    needs: [build-publish]
    if: github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      website-devl-fqdn: "test1.rrchnm.org"
      website-prod-fqdn: "test1.rrchnm.org"
